### ISSUE TITLE
Make Preconfigured Page Renderers automatically configurable from the config file

### ISSUE THREAD

**Issue by katheroine** [katheroine/layin#28]
Now, the all derivatives of the `AbstractVioletPreconfiguredPageRenderer` class have to deliver method `providePreconfiguration` with an argument being array with all needed configuration fields, eg.:
```php
class IndexPreconfiguredPageRenderer extends AbstractVioletPreconfiguredPageRenderer {
  protected function providePreconfiguration(): array {
    return [
      'templates_dir_absolute_path' => __DIR__ . '/../../templates',
      'template_local_path' => '',
      'config_dir_path' => '../../config',
      'base_url' => '../..',
      'subpages_relative_url' => 'pages',
      'assets_dir_relative_path' => '../assets',
      'code_file_extension' => 'php',
      'is_debug_mode' => false,
    ];
  }
```

Make it an option (method `providePreconfiguration` shouldn't be obligatory) and let it be automatically configurable by the file `pages_config.yaml`, eg.:
```yaml
- id: index
  base_relative_url: '..'
  subpages_relative_url: 'pages'
  config_dir_relative_path: '../../config'
  assets_dir_relative_path: '../assets'
  templates_dir_absolute_path: __DIR__ . '/../../public/templates'
  template_prefix_path: ''
  template_name: 'index.layin.twig.html'
- id: layouts
  base_relative_url: '../../..'
  subpages_relative_url: '../../../pages'
  config_dir_relative_path: '../../../../config'
  assets_dir_relative_path: '../../../assets'
  templates_dir_absolute_path: __DIR__ . '/../../../templates'
  template_prefix_path: 'layouts/'
  groups:
    - id: board
      template_prefix_path: 'board/'
      pages:
        - id: one_column
          template_name: 'one_column.layin.twig.html'
        - id: two_columns
          template_name: 'two_columns.layin.twig.html'
        - id: three_columns
          template_name: 'three_columns.layin.twig.html'
```
